CREATE TABLE ACCOUNT_INFO (
	"ID" NUMBER(12) NOT NULL ,
	"USERNAME" VARCHAR2(64 BYTE) NULL ,
	"PASSWORD" VARCHAR2(64 BYTE) NULL ,
	"GENDER" CHAR(1 BYTE) NULL ,
	"EMAIL" VARCHAR2(64 BYTE) NULL ,
	"CREATE_DATE" DATE NULL 
)
select ACCOUNT_SEQ.NEXTVAL from dual;


